### ISSUE TITLE
multiprocessing.Pool() not run in Parallel

### ISSUE THREAD

**Issue by HongxuanZhang** [stanford-futuredata/POP#4]
Hi there!

When I ran your code, I found that in the [traffic_engineering/lib/algorithms/pop.py](https://github.com/stanford-futuredata/POP/blob/main/traffic_engineering/lib/algorithms/pop.py) file, you used the module pathos.multiprocessing in code pool = multiprocessing.ProcessPool(NUM_CORES) in line 188. But I found the processes are not running in parallel, my CPU has only one core occupied, I am wondering that whether this phenomenon is correct? 

Thanks for your reply!

**Comment by fabuzaid21** [comment]
Hi @HongxuanZhang!

Thanks for the question. Yes, by default, the `DEBUG` flag is set to `True` in `pop.py`, so the code will not spawn multiple processes and solve the sub-problems in parallel.

In fact, we discovered that setting the `DEBUG` flag to `False` doesn't work, either, due to the Gurobi's global lock. (AFAIK, it's not possible to spawn multiple instances of the Gurobi solver simultaneously.) So, for now you should keep `DEBUG = True`, and I will push an update to the codebase that corrects this.

**Comment by HongxuanZhang** [comment]
Thanks for your reply.
